# greetd config
[terminal]
vt = 1

[default_session]
# Pré-remplit le champ utilisateur avec TARGET_USER dans l’UI
command = "/usr/bin/tuigreet --config /etc/tuigreet.toml --sessions /usr/share/wayland-sessions:/usr/share/xsessions --user __TARGET_USER__"
# Le greeter tourne en 'greeter' (plus sûr). Si tu veux le lancer avec ton user, remplace par user="__TARGET_USER__".
user = "__TARGET_USER__"
